name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Checking Multi-Line Shell command
        run: |
          echo "First Output"
          echo "Second Output"
